config/routes.rb
Admin::Engine.routes.draw do
    # For admin interface
  root to: 'admin#show'
  get '/index', to: 'admin#index'
  get '/show', to: 'admin#show'
  get '/new', to: 'admin#new'
  post '/admin', to: 'admin#create'
  get '/edit', to: 'admin#edit'
  patch '/admin', to: 'admin#update'
  get '/destroy', to: 'admin#destroy'
end

app/models/admin/application_record.rb
module Admin
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true

    def self.attributes
      self.column_names.reject { |col| Ignored_attributes.include? col }.reject { |col| self.associations.map { |a| a.foreign_key.to_s }.include? col}
    end
    
    def self.associations
      self.reflect_on_all_associations
    end

    def display
      "#{self.class.name.demodulize} #{self.id}"
    end
  end
end

app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ApplicationController
    include Pagy::Backend
    include ActionController::MimeResponds
    layout 'layouts/admin/application'

    before_action :set_object, only: [:edit, :destroy]
    after_action -> { flash.discard }, if: -> { request.xhr? }

    # Overides strong params
    def params
      request.parameters
    end

    def dashboard
    end

    def index
      # handle where
      if params[:where].blank?; 
        params[:where] = "1 = 1"
      else @where = params[:where]; end
      # handle includes
      if params[:includes].blank? || params[:includes].kind_of?(Array)
        @includes = params[:includes]
      else @includes = params[:includes].split(' '); end
      # handle sorting
      if params[:sort_by].present? && params[:class].present?
        @class = params[:class]; @attribute = params[:sort_by]; end
      # actual controller stuff
      if params[:model].present?
        @pagy, @objects = pagy(params[:model].constantize.
          includes( JSON.parse(@includes.to_json) ).
          where( Arel.sql(params[:where]) ).
          reorder( Arel.sql("#{params[:sort_by]} #{params[:sort_how]}") ), 
          link_extra: 'data-remote="true"') unless params[:model].blank?
        # still need class info if blank, create new!
        if @objects.blank?; @objects = [params[:model].constantize.new] end
        respond_to do |format|
          format.html
          format.js
        end
      end
    end

    def show
      @object = params[:model].constantize.find(params[:id]) unless params[:model].blank? || params[:id].blank?
      respond_to do |format|
        format.js
        format.html
      end
    end

    def new
      @object = params[:model].constantize.new()
      respond_to do |format|
        format.js
        format.html
      end
    end

    def edit
      respond_to do |format|
        format.js
        format.html
      end
    end

    def create
      @object = params[:object][:model].constantize.new(params[:object].except(:model, :id))
      respond_to do |format|
        if @object.save
          flash[:success] = "Succesfully created #{@object.class.name.demodulize} #{@object.id}."
          format.js { render 'show', model: params[:object][:model]}
        else
          flash[:danger] = "Failed to create #{@object.class.name.demodulize}."
          format.js { render 'new', model: params[:object][:model]}
        end
      end
    end

    def update
      respond_to do |format|
        @object = params[:object][:model].constantize.find(params[:object][:id])
        @updated = @object.update(params[:object].except(:model, :id))
        if @updated
          flash[:success] = "Succesfully updated #{@object.class.name.demodulize} #{@object.id}."
        else
          flash[:danger] = "Failed to update #{@object.class.name.demodulize}."
        end
        format.js
      end
    end

    def destroy
      if @object.destroy || @object.deleted_at.present?
        flash[:success] = "Successfully destroyed #{@object.class.name.demodulize} #{@object.id}."
      else
        flash[:danger] = "Failed to destroy #{@object.class.name.demodulize} #{@object.id}."
      end
      respond_to do |format|
        format.js
      end
    end

    private
      def set_object
        @object = params[:model].constantize.find(params[:id])
      end
  end
end

app/controllers/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
    include ::ActionView::Layouts
    layout 'application'
  end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
  include FontAwesome::Rails::IconHelper;
  include Pagy::Frontend;

  def app_models
    x = Rails.configuration.eager_load_namespaces
    x.delete(ActiveStorage::Engine)
    x.each(&:eager_load!)
    mdls = Hash[ActiveRecord::Base.descendants.reject{ |v| v.name == "Admin::ApplicationRecord" || v.name == 'ActiveStorage::Blob::Analyzable' || v.name == 'Thickness::ThicknessRecord'|| v.name == 'ApplicationRecord' || v.name == "ActiveRecord::SchemaMigration" || v.name.safe_constantize.blank? }.map(&:name).collect { |v| [v, v.constantize.reflect_on_all_associations.map(&:name) ] }]
    models = {}
    mdls.each do |model|
      if models[model[0].constantize.to_s].present?
        puts 'WKF:JLDDJFLKDSJFLDSKFJDSJFJDSJFLDJSFJldsjfdjsflksd'
      end
      unless model[0].blank? 
        models[model[0].constantize.parent.to_s] ||= []
        models[model[0].constantize.parent.to_s] << model
      end
    end
    models["Object"] = models.delete("Object")
    models.delete("ActiveStorage")
    models.each do |section|
      if section[0].include?('::') && models[section[0].split('::').first].present?
        old = models[section[0].split('::').first]
        models[section[0].split('::').first].each_with_index do |value, index|
          if value[0].to_s == section[0].to_s
            temp =  old.delete_at(index)
            section[1].insert(0, temp)
          end
        end
      end
    end
    return models
  end

  def page_title
    if action_name == 'index'
      "#{controller_name.classify} #{action_name}".titleize
    else
      "#{action_name} #{controller_name.classify}".titleize
    end
  end

  # Links
  def admin_association_link(association, object)
    case association.macro.to_s
    when 'belongs_to' 
      admin_link(object.send(association.name)) 
    when 'has_one' 
      admin_link(object.send(association.name))
    when 'has_many' 
      admin_collection_link(object.send(association.name), association, object)
    when 'has_one :through'
      admin_link(object.send(association.name)) 
    when 'has_many :through' 
      admin_collection_link(object.send(association.name), association, object)
    when 'has_and_belongs_to_many' 
      admin_collection_link(object.send(association.name), association, object)
    end 
  end

  def admin_collection_link(collection, association, object)
    output = "<a class='collapse-btn collapsed' data-toggle='collapse' href='##{association.name}#{object.id}'>[ + ]</a>
    <span class='badge badge-secondary'>
      #{collection.length}
    </span>
    <div class='collapse' id='#{association.name}#{object.id}'>"
    collection.each do |col|
      output << admin_link(col) << '<br>'
    end
    output << "</div>"
    return output.html_safe
  end

  def admin_link(object)
      link_to object.display, show_path(model: "#{object.class.name.constantize}", id: object.id ), class:'' unless object.blank?
  end

  # Form fields
  def admin_association_form_field(association, form)
    case association.macro.to_s
    when 'belongs_to' 
      form.association association.name, label_method: :display
    when 'has_one' 
      # form.association association.name, label_method: :display
    when 'has_many'
      form.association association.name, label_method: :display
    when 'has_one :through'
      # form.association association.name, label_method: :display 
    when 'has_many :through'
      # form.association association.name, label_method: :display
    when 'has_and_belongs_to_many'
      form.association association.name, style: 'height: 600px;', label_method: :display
    end 
  end

  def get_attributes(model)
    ignored_attributes = ['deleted_at', 'id', 'remember_digest'] + Rails.application.config.filter_parameters.map { |a| a.to_s }

    model.column_names.reject { |col| ignored_attributes.include? col }.reject { |col| get_associations(model).map { |a| a.foreign_key.to_s }.include? col}
  end

  def get_associations(model)
    model.reflect_on_all_associations
  end

  def admin(text, model, options={})
    link_to raw("#{text}&nbsp;<span class='badge badge-secondary pull-right'>#{model.constantize.count}</span>"), index_path(model: model, includes: options[:includes]), style: 'text-align: left !important;',class: 'admin_btn ' + options[:class], data: {model: "#{model.constantize}", includes: options[:includes], disable_with: fa_icon('spinner spin', text: '<small>*thinking...*</small>'.html_safe)}
  end
end

app/views/admin/admin/_form.html.erb
<div class='container-fluid border rounded px-2 py-2 text-center'>
  <h2>
    <% if @object.persisted? -%> 
      Edit <code><%= @object.class.name %></code> <%= @object.id %>
    <% else -%>
      New <code><%= @object.class.name %></code> 
    <% end -%>
  </h2>
  <%= link_to fa_icon('list', text: 'index'), index_path(model: @object.class.name), class: 'admin_btn btn btn-outline-secondary', remote: true, data: { model: @object.class.name } %>
</div>
<div class='card my-3'>
  <div class='card-body'>
    <%= simple_form_for @object, as: :object, url: admin_path, remote: true do |form| %>
      <%= form.hidden_field :model, value: @object.class.name %>
      <%= form.hidden_field :id, value: @object.id %>

      <% get_attributes(@object.class).each do |attribute| -%>
        <%= form.input attribute, include_hidden: false, include_blank: true %>
      <% end -%>
      
      <% get_associations(@object.class).each do |association| -%>
        <%= admin_association_form_field(association, form) %>
      <% end -%>
      <%= form.submit "Submit", class: "btn btn-secondary" %>
    <% end -%>
  </div>
</div>

app/views/admin/admin/_row.html.erb
<% bg_color = 'background-color: #efefef;' unless thing_counter.even? -%>
<div class='row' style='<%= bg_color %>' id='<%= thing.class.name.demodulize %><%= thing.id %>'>
  <div class='col-md-2' style='<%= bg_color %>'>
    <%= thing.id %>
  </div>
  <% get_attributes(thing.class).each do |attribute| -%>
      <% next if attribute.include?('encrypted') && attribute.include?('_iv') -%>
    <div class='col-md-2' style='<%= bg_color %> overflow-x: auto;'>
      <% case thing[attribute] -%>
      <% when Time -%>
        <samp><%= thing[attribute].strftime("%D @ %T") %></samp>
      <% when Integer -%>
        <kbd><%= thing[attribute] %></kbd>
      <% when Float -%>
        <kbd><%= thing[attribute] %></kbd>
      <% when TrueClass -%>
        <div class='text-success'><%= thing[attribute] %></div>
      <% when FalseClass -%>
        <div class='text-danger'><%= thing[attribute] %></div>
      <% when NilClass -%>
        ---
      <% else -%>
        <% if attribute.include?('encrypted') -%>
          <%= thing.send(attribute.remove('encrypted_')) %>
        <% else %>
          <%= thing[attribute] %>
        <% end -%>
      <% end -%>
    </div>
  <% end -%>
  <% get_associations(thing.class).each do |association| -%>
    <div class='col-md-2' style='<%= bg_color %> overflow-x: auto;'>
      <%= admin_association_link(association, thing) %>
    </div>
  <% end -%>
  <div class='col-md-2 text-right' style='<%= bg_color %>'>
    <div class='btn-group' role='group'>
      <%= link_to fa_icon('eye'),             
            show_path(model: "#{thing.class.name.constantize}", id: thing.id), 
            class: 'font-weight-bold btn btn-sm', 
            title: 'Show' %>
      <%= link_to fa_icon('pencil'), 
            edit_path(model: "#{thing.class.name.constantize}", id: thing.id),
            class: 'font-weight-bold btn btn-sm',
            title: 'Edit',
              data: { toggle: 'tooltip' } %>
      <%= link_to fa_icon('times'), 
            destroy_path(model: "#{thing.class.name.constantize}", id: thing.id),            
            class: 'font-weight-bold btn btn-sm',
            title: 'Delete',
            remote: true,
              data: { confirm: 'Are you sure?', 
                      toggle: 'tooltip' } %>
      <small class='text-muted my-auto'>id:<%= thing.id %></small>
    </div>
  </div>
</div>

app/views/admin/admin/_show.html.erb
<div class='container-fluid border rounded px-2 py-2 text-center'>
  <h2>Show <code><%= @object.class.name %></code> <%= @object.id %></h2>
  <%= link_to fa_icon('list', text: 'index'), index_path(model: @object.class.name), class: 'admin_btn btn btn-outline-secondary', remote: true, data: { model: @object.class.name } %>
  <%= link_to fa_icon('pencil', text: 'edit'), edit_path(model: @object.class.name, id: @object.id), class: 'admin_btn btn btn-outline-secondary', remote: true, data: { model: @object.class.name, id: @object.id } %>
</div>

<div class='card my-3'>
  <div class='card-header'>
    <h4><strong>Attributes</strong></h4>
  </div>
  <div class='card-body'>
    <%= "<div class='mx-3'> No attributes to display...</div>".html_safe unless get_attributes(@object.class).present? %>
    <% get_attributes(@object.class).each do |attribute| -%>
      <div class='form-group'>       
        <label class='form-control-label' style='font-size: 18px;'><%= attribute.titleize %></label>
        <% unless @object[attribute].nil? -%>
          <div class='container-fluid border rounded mx-0 bg-secondary-light'>
            <% case @object[attribute] -%>
            <% when Time -%>
              <samp><%= @object[attribute].strftime("%D @ %T") %></samp>
            <% when Integer -%>
              <kbd><%= @object[attribute] %></kbd>
            <% when Float -%>
              <kbd><%= @object[attribute] %></kbd>
            <% when TrueClass -%>
              <div class='text-success'><%= @object[attribute] %></div>
            <% when FalseClass -%>
              <div class='text-danger'><%= @object[attribute] %></div>
            <% when NilClass -%>
              ---
            <% else -%>
              <%= @object[attribute] %>
            <% end -%>
          </div>
        <% end -%>
      </div>
    <% end -%>
  </div>
</div>

<div class='card my-3'>
  <div class='card-header'>
    <h4><strong>Associations</strong></h4>
  </div>
  <div class='card-body'>
    <%= "No associations to display..." unless get_associations(@object.class).present? %>
    <% get_associations(@object.class).each do |association| -%>
      <% unless association.name.to_s == 'files_blobs' -%>
        <div class='form-group'>       
          <label class='form-control-label' style='font-size: 18px;'>
            <%= association.name.to_s.titleize %>
          </label>
          <% unless @object.send(association.name).blank? -%>
            <div class='container-fluid border rounded mx-0 bg-secondary-light'>
              <% if association.name.to_s == 'files_attachments' -%>
                <% @object.send(association.name).each do |file| -%>
                  <% if file.previewable? -%>
                    <%= link_to image_tag(main_app.url_for(file.preview(resize: "200"))), main_app.rails_blob_path(file, disposition: :inline), target: '_blank' %>
                  <% elsif file.variable? -%>
                    <%= link_to image_tag(main_app.url_for(file.variant(resize: "200"))), main_app.rails_blob_path(file, disposition: :inline), target: '_blank' %>
                  <% else -%>
                    <%= link_to "#{file.filename}", main_app.rails_blob_path(file, disposition: :inline), target: '_blank' %>
                  <% end -%>
                <% end -%>
              <% else -%>
                <%= admin_association_link(association, @object) %>
              <% end -%>
            </div>
          <% end -%>
        </div>
      <% end -%>
    <% end -%>
  </div>
</div>

app/views/admin/admin/create.js.erb
<% if @object.persisted? -%>
  $("#content_area > *:not('#history_area')").remove();
  $('#content_area').append('<%= j render partial: 'show' %>')
  $("ul").find(`[data-model='<%= @object.class.name %>']`).css('background-color', 'red')

  count = $(`a[data-model='<%= @object.class.name %>']>span`)
  count.text(parseInt(count.text()) + 1)
<% end -%>
flash('<%= j render 'layouts/flash' %>');

app/views/admin/admin/destroy.js.erb
$('#<%= @object.class.name.demodulize %><%= @object.id %>').remove();
$.each($('div[id="<%= @object.class.name.demodulize %><%= @object.id %>_history"]'), function(key,value){
  $(value).remove();
})
count = $(`a[data-model='<%= @object.class.name %>']>span`)
count.text(count.text() - 1)
flash('<%= j render 'layouts/flash' %>');
<% flash.discard %>

app/views/admin/admin/edit.html.erb
<%= render 'form' %>

app/views/admin/admin/edit.js.erb
$('#content_area').empty().append('<%= j render partial: 'form' %>');
flash('<%= j render 'layouts/flash' %>');

app/views/admin/admin/index.html.erb
<%= render 'index' %>

app/views/admin/admin/index.js.erb
$('#filter_submit').attr('disabled', false);
$(".dropdown-menu.show").dropdown('toggle')
$('#content_area').empty().append('<%= j render partial: 'index' %>')
<% unless @attribute == " " && @class == " " -%>
  $("#header_<%= @objects.first.class.name.demodulize %><%= @attribute %>").addClass('<%= @class %>').html(('<%= @class == 'sort_up' ? fa_icon('sort-up', text: @attribute):fa_icon('sort-down', text: @attribute) %>'))
<% end -%>

$('#where').val('<%= @where.html_safe unless @where.blank? %>')
$('#where_storage').data('where', '<%= @where.html_safe unless @where.blank? %>')
flash('<%= j render 'layouts/flash' %>');

app/views/admin/admin/new.html.erb
<%= render 'form' %>

app/views/admin/admin/new.js.erb
$('#content_area').empty().append('<%= j render partial: 'form' %>')
flash('<%= j render 'layouts/flash' %>');

app/views/admin/admin/show.html.erb
<%= @object.present? ? (render 'show') : (' ') %>

app/views/admin/admin/show.js.erb
$('#content_area').empty().append('<%= j render partial: 'show' %>');
flash('<%= j render 'layouts/flash' %>');

app/views/admin/admin/update.js.erb
$('.invalid-feedback').remove();
$('.is-invalid').removeClass('is-invalid');
<% @object.errors.each do |attribute, error| -%>
$('#object_<%= attribute %>').addClass('is-invalid')
$('#object_<%= attribute %>').after(`<div class='invalid-feedback'><%= error %></div>`)
<% end -%>
<% if @updated -%>
  $("#content_area > *:not('#history_area')").remove();
  $('#content_area').append('<%= j render partial: 'show' %>')
<% end -%>
flash('<%= j render 'layouts/flash' %>');

app/views/layouts/admin/_flash.html.erb
<% flash.each do |message_type, message| -%>
    <% case message_type -%>
    <% when 'notice' -%>
      <% message_type = "primary" -%>
    <% when 'alert' -%>
      <% message_type = "warning" -%>
    <% end -%>
    <div class="alert alert-<%= message_type %> mt-0 mb-3"
          role="alert">
      <strong><%= message.html_safe %></strong>
      <button type="button"
              class="close text-<%= message_type %>"
              data-dismiss="alert"
              aria-label="Close">
        <span aria-hidden="true"><%= fa_icon 'times' %></span>
      </button>
    </div>
  <% end -%>

app/views/layouts/admin/_sidebar.html.erb
<div class='col-2'>
    <div class='card'>
      <div class='card-body text-center'>
        <%= 'namespaces'.html_safe unless app_models.first[0] == 'Object' %>
        <% app_models.each do |scope| -%>
          <% if scope[0] == 'Object' -%>
            <%= '<hr>'.html_safe unless app_models.first[0] == 'Object' %>
            non-scoped models
            <% scope[1].each do |model| -%>
              <%= admin model[0].demodulize.downcase.pluralize, model[0], {class: 'btn btn-primary btn-block text-right my-2', includes: model[1] } %>
            <% end unless scope[1].blank? -%>
            <hr>
          <% else -%>
            <div class='dropdown' id='<%= scope[0] %>_dropdown'>
              <button class="btn btn-primary text-left btn-block dropdown-toggle my-2" type="button" id='<%= scope[0] %>_dropdown_btn' data-toggle="dropdown">
                <%= scope[0] %>
              </button>
              <div class='dropdown-menu dropdown-menu-right'>
                <% scope[1].each do |model| -%>
                  <%= admin model[0].demodulize.downcase.pluralize, model[0], {class: 'dropdown-item ', includes: model[1] } %>
                <% end -%>
              </div>
            </div>
          <% end -%>
        <% end -%>
      </div>
    </div>
  </div>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>admin</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "admin/application", media: "all" %>
    <%= javascript_include_tag "admin/application" %>
    <meta name="turbolinks-cache-control" content="no-cache">
  </head>
  <body>
    <div class="container-fluid py-2" id='wrapper'>
      <%= render partial: 'layouts/admin/flash' %>
      <div class='form-row'>
        <%= render partial: 'layouts/admin/sidebar' %>
        <div class='col-10'>
          <div id='content_area'>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>